[package]
name = "astroport-tests"
version = "1.0.0"
authors = ["astroport"]
edition = "2018"
repository = "https://github.com/astroport-fi/astroport-governance"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.15"
classic-bindings = "0.1.1"
cosmwasm-std = "1.1"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

cosmwasm-schema = "1.1"
cw-multi-test = "0.15"
astroport = {git = "https://github.com/classic-terra/astroport-core.git", branch = "terra_classic_invictus", package = "astroport"}
astroport-token = {git = "https://github.com/classic-terra/astroport-core.git", branch = "terra_classic_invictus", package = "astroport-token"}
astroport-escrow-fee-distributor = {path = "../../contracts/escrow_fee_distributor", default-features = false, package = "astroport-escrow-fee-distributor"}
astroport-governance = { path = "../astroport-governance"}
astroport-staking = { git = "https://github.com/classic-terra/astroport-core.git", branch = "terra_classic_invictus", package = "astroport-staking"}
astroport-voting-escrow = {path = "../../contracts/voting_escrow", package = "voting-escrow" }
anyhow = "1"